### ISSUE TITLE
Additional yum package dependency

### ISSUE THREAD

**Issue by iluliaq** [sdsc/R-roll#2] opened 2018-10-09 15:03 UTC
Attempting to compile the roll, I got the error below.  After studying the error it appears as though <code>readline-devel</code> is a required package for <code>R</code> to compile.  The roll compiled properly after running <code>yum install readline-devel</code> so perhaps that could be added to <code>bootstrap.sh</code> even though it appears to be an <code>R</code> requirement for the default configuration and not directly an <code>R-roll</code> requirement.

<code><pre>
checking for cos in -lm... yes
checking for sin in -lm... yes
checking for dlopen in -ldl... yes
checking readline/history.h usability... no
checking readline/history.h presence... no
checking for readline/history.h... no
checking readline/readline.h usability... no
checking readline/readline.h presence... no
checking for readline/readline.h... no
checking for rl_callback_read_char in -lreadline... no
checking for main in -lncurses... yes
checking for rl_callback_read_char in -lreadline... no
configure: error: --with-readline=yes (default) and headers/libs are not available
make[6]: Entering directory `/export/data/sdsc/R-roll/BUILD/sdsc-R-3.5.1/R-3.5.1'
make[6]: *** No targets specified and no makefile found.  Stop.
make[6]: Leaving directory `/export/data/sdsc/R-roll/BUILD/sdsc-R-3.5.1/R-3.5.1'
make[5]: *** [build] Error 2
make[5]: Leaving directory `/export/data/sdsc/R-roll/BUILD/sdsc-R-3.5.1'
make[4]: *** [build] Error 2
make[4]: Leaving directory `/export/data/sdsc/R-roll/BUILD/sdsc-R-3.5.1'
error: Bad exit status from /var/tmp/rpm-tmp.0FDo7i (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.0FDo7i (%build)
make[3]: *** [rpm] Error 1
make[3]: Leaving directory `/export/data/sdsc/R-roll/src/R'
make[2]: *** [rpm] Error 2
make[2]: Leaving directory `/export/data/sdsc/R-roll/src'
make[1]: *** [rpms] Error 2
make[1]: Leaving directory `/export/data/sdsc/R-roll'
make: *** [default] Error 2
</pre></code>

**Comment by tcooper** [comment] 2018-10-09 20:09
On which version of Rocks and which node type (ie. frontend or devel server) were you attempting to build the R-roll?

**Comment by iluliaq** [comment] 2018-10-10 14:46
I was building it on a frontend server to add to the compute nodes kickstart, on a fresh install of Rocks 7.0 (Manzanita) after installing CentOS <code>os</code> and <code>update</code> rolls created according to the docs.   Installed rolls are:
<code><pre>
NAME                      VERSION    ARCH   ENABLED
area51:                   7.0        x86_64 yes    
base:                     7.0        x86_64 yes    
CentOS:                   7.4.1708   x86_64 yes    
core:                     7.0        x86_64 yes    
fingerprint:              7.0        x86_64 yes    
ganglia:                  7.0        x86_64 yes    
hpc:                      7.0        x86_64 yes    
htcondor:                 8.6.8      x86_64 yes    
kernel:                   7.0        x86_64 yes    
kvm:                      7.0        x86_64 yes    
perl:                     7.0        x86_64 yes    
python:                   7.0        x86_64 yes    
sge:                      7.0        x86_64 yes    
Updates-CentOS-7.4.1708:  2017-12-01 x86_64 yes    
zfs-linux:                0.7.3      x86_64 yes    
sdsc:                     7.0        x86_64 yes    
Centos_7_update_20181004: 7.0        x86_64 yes    
Centos_7_os_20181004:     7.0        x86_64 yes    
gnucompiler:              7.0        x86_64 yes    
cmake:                    7.0        x86_64 yes    
gnutools:                 7.0        x86_64 yes    
R:                        7.0        x86_64 yes    
mpi:                      7.0        x86_64 yes  
</pre></code>

**Comment by tcooper** [comment] 2018-10-10 17:28
I've confirmed the behavior on a vanilla Rocks frontend and verified the problem does not exist in our environment because of two things:

1. We build rolls on a development appliance and this package is added to the definition of that node type explicitly.
2. We add this package explicitly in custom configuration of our frontends.

We'll add the requirement to the README of the R-roll and discuss whether adding it to the bootstrap is also warranted.

Thanks for reporting.

**Comment by tcooper** [comment] 2019-06-19 22:00
Resolved in commit [9acfc32c](https://github.com/sdsc/R-roll/commit/9acfc32cf3ab0501de8b5002f03db25d54796cae)

**Closed as completed by tcooper** 2019-06-19 22:00 UTC
